export const JobList = [
  {
    id: 293,
    jobTitle: "Network Engineer",
    company: "Wipro",
    location: "Pune",
    link: "https://careers.wipro.com/careers-home/jobs/3114949",
    logo: "/static/img/hp.png",
    salary: "$$",
  },
  {
    id: 2934,
    jobTitle: "Network Engineer",
    company: "Wipro",
    location: "Pune",
    link: "https://careers.wipro.com/careers-home/jobs/3114949",
    logo: "/static/img/hp.png",
    salary: "$$",
  },
  {
    id: 2935,
    jobTitle: "Network Engineer",
    company: "Wipro",
    location: "Pune",
    link: "https://careers.wipro.com/careers-home/jobs/3114949",
    logo: "/static/img/hp.png",
    salary: "$$",
  },
  {
    id: 293,
    jobTitle: "Network Engineer",
    company: "Wipro",
    location: "Pune",
    link: "https://careers.wipro.com/careers-home/jobs/3114949",
    logo: "/static/img/hp.png",
    salary: "$$",
  },
  {
    id: 2934,
    jobTitle: "Network Engineer",
    company: "Wipro",
    location: "Pune",
    link: "https://careers.wipro.com/careers-home/jobs/3114949",
    logo: "/static/img/hp.png",
    salary: "$$",
  },
  {
    id: 2935,
    jobTitle: "Network Engineer",
    company: "Wipro",
    location: "Pune",
    link: "https://careers.wipro.com/careers-home/jobs/3114949",
    logo: "/static/img/hp.png",
    salary: "$$",
  },
  {
    id: 293,
    jobTitle: "Network Engineer",
    company: "Wipro",
    location: "Pune",
    link: "https://careers.wipro.com/careers-home/jobs/3114949",
    logo: "/static/img/hp.png",
    salary: "$$",
  },
  {
    id: 2934,
    jobTitle: "Network Engineer",
    company: "Wipro",
    location: "Pune",
    link: "https://careers.wipro.com/careers-home/jobs/3114949",
    logo: "/static/img/hp.png",
    salary: "$$",
  },
  {
    id: 2935,
    jobTitle: "Network Engineer",
    company: "Wipro",
    location: "Pune",
    link: "https://careers.wipro.com/careers-home/jobs/3114949",
    logo: "/static/img/hp.png",
    salary: "$$",
  },
  {
    id: 293,
    jobTitle: "Network Engineer",
    company: "Wipro",
    location: "Pune",
    link: "https://careers.wipro.com/careers-home/jobs/3114949",
    logo: "/static/img/hp.png",
    salary: "$$",
  },
  {
    id: 2934,
    jobTitle: "Network Engineer",
    company: "Wipro",
    location: "Pune",
    link: "https://careers.wipro.com/careers-home/jobs/3114949",
    logo: "/static/img/hp.png",
    salary: "$$",
  },
  {
    id: 2935,
    jobTitle: "Network Engineer",
    company: "Wipro",
    location: "Pune",
    link: "https://careers.wipro.com/careers-home/jobs/3114949",
    logo: "/static/img/hp.png",
    salary: "$$",
  },
];
